package auth

import (
	"context"

	"github.com/hubvas/internal/domain/identity"
	"github.com/hubvas/internal/domain/shared"
)

// TokenService defines the contract for JWT token generation and validation.
// It is implemented in the infrastructure layer (infrastructure/auth/jwt.go).
type TokenService interface {
	GenerateAccessToken(userID identity.UserID) (string, int64, error)
	GenerateRefreshToken(userID identity.UserID) (string, error)
	ValidateAccessToken(tokenString string) (identity.UserID, error)
	ValidateRefreshToken(tokenString string) (identity.UserID, error)
}

// PasswordService defines the contract for password hashing.
type PasswordService interface {
	Hash(password string) (string, error)
	Verify(password, hash string) bool
}

// AuthApplicationService orchestrates authentication use cases.
type AuthApplicationService struct {
	userRepo    identity.UserRepository
	tokenSvc    TokenService
	passwordSvc PasswordService
}

// NewAuthApplicationService creates the application service.
func NewAuthApplicationService(
	userRepo identity.UserRepository,
	tokenSvc TokenService,
	passwordSvc PasswordService,
) *AuthApplicationService {
	return &AuthApplicationService{
		userRepo:   userRepo,
		tokenSvc:   tokenSvc,
		passwordSvc: passwordSvc,
	}
}

// Register creates a new user account and returns both the user and tokens
// so the client can immediately authenticate without a second login request.
func (s *AuthApplicationService) Register(ctx context.Context, req RegisterRequest) (*RegisterResponse, error) {
	// Check uniqueness.
	exists, err := s.userRepo.ExistsByUsername(ctx, req.Username)
	if err != nil {
		return nil, err
	}
	if exists {
		return nil, shared.NewDomainError(shared.ErrAlreadyExists, "username is taken")
	}

	exists, err = s.userRepo.ExistsByEmail(ctx, req.Email)
	if err != nil {
		return nil, err
	}
	if exists {
		return nil, shared.NewDomainError(shared.ErrAlreadyExists, "email is already registered")
	}

	// Hash password.
	hash, err := s.passwordSvc.Hash(req.Password)
	if err != nil {
		return nil, err
	}

	// Create aggregate (ID=0 means auto-generated by the repo).
	user, err := identity.NewUser(0, req.Username, req.Email, hash)
	if err != nil {
		return nil, err
	}

	if err := s.userRepo.Save(ctx, user); err != nil {
		return nil, err
	}

	// Generate tokens immediately so the user is auto-logged-in.
	accessToken, expiresAt, err := s.tokenSvc.GenerateAccessToken(user.ID())
	if err != nil {
		return nil, err
	}

	refreshToken, err := s.tokenSvc.GenerateRefreshToken(user.ID())
	if err != nil {
		return nil, err
	}

	return &RegisterResponse{
		User: &UserDTO{
			ID:        int64(user.ID()),
			Username:  user.Username(),
			Email:     user.Email(),
			AvatarURL: user.AvatarURL(),
			CreatedAt: user.CreatedAt(),
		},
		Tokens: &TokenResponse{
			AccessToken:  accessToken,
			RefreshToken: refreshToken,
			ExpiresAt:    expiresAt,
			TokenType:    "Bearer",
		},
	}, nil
}

// Login authenticates a user and returns tokens.
func (s *AuthApplicationService) Login(ctx context.Context, req LoginRequest) (*TokenResponse, error) {
	user, err := s.userRepo.FindByEmail(ctx, req.Email)
	if err != nil {
		return nil, shared.NewDomainError(shared.ErrUnauthorized, "invalid email or password")
	}

	if !s.passwordSvc.Verify(req.Password, user.PasswordHash()) {
		return nil, shared.NewDomainError(shared.ErrUnauthorized, "invalid email or password")
	}

	accessToken, expiresAt, err := s.tokenSvc.GenerateAccessToken(user.ID())
	if err != nil {
		return nil, err
	}

	refreshToken, err := s.tokenSvc.GenerateRefreshToken(user.ID())
	if err != nil {
		return nil, err
	}

	return &TokenResponse{
		AccessToken:  accessToken,
		RefreshToken: refreshToken,
		ExpiresAt:    expiresAt,
		TokenType:    "Bearer",
	}, nil
}

// Refresh validates a refresh token and issues a new token pair.
func (s *AuthApplicationService) Refresh(ctx context.Context, req RefreshRequest) (*TokenResponse, error) {
	userID, err := s.tokenSvc.ValidateRefreshToken(req.RefreshToken)
	if err != nil {
		return nil, shared.NewDomainError(shared.ErrUnauthorized, "invalid or expired refresh token")
	}

	// Verify the user still exists.
	_, err = s.userRepo.FindByID(ctx, userID)
	if err != nil {
		return nil, shared.NewDomainError(shared.ErrUnauthorized, "user not found")
	}

	accessToken, expiresAt, err := s.tokenSvc.GenerateAccessToken(userID)
	if err != nil {
		return nil, err
	}

	refreshToken, err := s.tokenSvc.GenerateRefreshToken(userID)
	if err != nil {
		return nil, err
	}

	return &TokenResponse{
		AccessToken:  accessToken,
		RefreshToken: refreshToken,
		ExpiresAt:    expiresAt,
		TokenType:    "Bearer",
	}, nil
}

// GetUser retrieves a user by ID.
func (s *AuthApplicationService) GetUser(ctx context.Context, userID identity.UserID) (*UserDTO, error) {
	user, err := s.userRepo.FindByID(ctx, userID)
	if err != nil {
		return nil, err
	}
	return &UserDTO{
		ID:        int64(user.ID()),
		Username:  user.Username(),
		Email:     user.Email(),
		AvatarURL: user.AvatarURL(),
		CreatedAt: user.CreatedAt(),
	}, nil
}
